version: '3'

services:
  labkey:
    image: lk:18.2
#    network_mode: host
    build:
      context: .
    container_name: labkey182
    depends_on:
      - db_pg12
    ports:
      - 8080:8080
    environment:
      - JDBC_DATABASE_URL=jdbc:postgresql://db_pg12/postgres
  db_pg12:
     image: postgres:12
     container_name: db_pg12
     network_mode: host
     restart: always
     volumes:
       - ./db_data:/var/lib/postgresql/data/
     environment:
       POSTGRES_USER: postgres
       POSTGRES_PASSWORD: postgres
       POSTGRES_DB: postgres
     ports:
       - 5432:5432
volumes:
   db_data:
